apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-backup-postgres-to-postgres
  namespace: default
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: postgres-ha
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: backup-postgres
      ports:
        - protocol: TCP
          port: 5432
