apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alert-rules
  namespace: default
data:
  alerts.yml: |
    groups:
      - name: devops-assessment-alerts
        rules:

          - alert: HighHTTP5xxRate
            expr: |
              (
                sum(rate(nginx_ingress_controller_requests{status=~"5.."}[5m]))
                /
                sum(rate(nginx_ingress_controller_requests[5m]))
              ) > 0.05
            for: 5m
            labels:
              severity: warning
              component: ingress
            annotations:
              summary: "HTTP 5xx rate above 5%"
              description: "Ingress HTTP 5xx error rate has exceeded 5% for 5 minutes."

          - alert: DatabasePVCUsageHigh
            expr: |
              (
                kubelet_volume_stats_used_bytes
                /
                kubelet_volume_stats_capacity_bytes
              ) * 100 > 85
            for: 5m
            labels:
              severity: warning
              component: storage
            annotations:
              summary: "Database PVC usage above 85%"
              description: "A persistent volume claim is using more than 85% of its capacity."

          - alert: PodCrashLoopBackOff
            expr: |
              kube_pod_container_status_waiting_reason{reason="CrashLoopBackOff"} > 0
            for: 2m
            labels:
              severity: critical
              component: kubernetes
            annotations:
              summary: "Pod container in CrashLoopBackOff"
              description: "A container has remained in CrashLoopBackOff for more than 2 minutes."
