apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: default
  labels:
    app: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: loki
          image: grafana/loki:3.2.1
          imagePullPolicy: IfNotPresent
          args:
            - -config.file=/etc/loki/local-config.yaml
          ports:
            - name: http
              containerPort: 3100
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 768Mi
          readinessProbe:
            httpGet:
              path: /ready
              port: 3100
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /ready
              port: 3100
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
          volumeMounts:
            - name: config
              mountPath: /etc/loki
            - name: storage
              mountPath: /loki
      volumes:
        - name: config
          configMap:
            name: loki-config
        - name: storage
          emptyDir: {}
